### ISSUE TITLE
SignatureException

### ISSUE THREAD

**Issue by linsea** [wangrunxiang/AndFixDemo#1]
```
/com.wangrunxiang.andfixdemo E/SecurityChecker: /data/data/com.wangrunxiang.andfixdemo/files/apatch/patch3.apatch
  java.security.SignatureException: error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length
      at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
      at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:349)
      at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:384)
      at com.alipay.euler.andfix.security.SecurityChecker.check(SecurityChecker.java:158)
      at com.alipay.euler.andfix.security.SecurityChecker.verifyApk(SecurityChecker.java:124)
      at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:127)
      at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:238)
      at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:165)
      at com.wangrunxiang.andfixdemo.MainActivity$3$1.onResponse(MainActivity.java:67)
      at com.wangrunxiang.andfixdemo.MainActivity$3$1.onResponse(MainActivity.java:52)
      at com.zhy.http.okhttp.OkHttpUtils$4.run(OkHttpUtils.java:194)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5539)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

@wangrunxiang 遇到这种错误，是不是补丁包没有签名？

**Comment by linsea** [comment]
@wangrunxiang 修复之后的代码呢？

**Comment by wangrunxiang** [comment]
@linsea 修复之后的代码通过补丁下发

**Comment by Smkai** [comment]
什么意思

**Comment by Smkai** [comment]
也是报这个错
